// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyNOABCF-bkcL-zoGryly5PTYijxt5qTk',
    appId: '1:338114903255:android:83f8717faa48781fbf4492',
    messagingSenderId: '338114903255',
    projectId: 'foodieglobe-fa7a9',
    storageBucket: 'foodieglobe-fa7a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrGzbqjJ_v0dYbOlWPMVksIedsyctqDjw',
    appId: '1:338114903255:ios:122e66ca6f021d13bf4492',
    messagingSenderId: '338114903255',
    projectId: 'foodieglobe-fa7a9',
    storageBucket: 'foodieglobe-fa7a9.firebasestorage.app',
    iosBundleId: 'com.example.restaurantGlobe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrGzbqjJ_v0dYbOlWPMVksIedsyctqDjw',
    appId: '1:338114903255:ios:122e66ca6f021d13bf4492',
    messagingSenderId: '338114903255',
    projectId: 'foodieglobe-fa7a9',
    storageBucket: 'foodieglobe-fa7a9.firebasestorage.app',
    iosBundleId: 'com.example.restaurantGlobe',
  );
}
