import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; // REQUIRED
import 'firebase_options.dart'; // GENERATED BY YOUR CLI
import 'screens/welcome_screen.dart';

// We will keep this here for now so your code doesn't break, 
// but we will soon replace it with a Stream from Firestore!
List<Map<String, dynamic>> mockVisits = []; 

void main() async {
  // 1. Mandatory for async main functions
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Initialize Firebase with your generated options
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyRestaurantApp());
}

class MyRestaurantApp extends StatelessWidget {
  const MyRestaurantApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'FoodieGlobe',
      theme: ThemeData(
        // Using your signature Midnight Navy / Blue color scheme
        primaryColor: const Color(0xff3a57e8),
        useMaterial3: true,
        brightness: Brightness.dark, // Better for a space-themed globe
      ),
      home: const WelcomeScreen(),
    );
  }
}